* Project - Overview: DSA-CLRS
** Following CLRS book and sharing the experience on discord
** The Various Data Structures and Algorithms will be together on this one project
** Project - Current Status
Ground-work laid for creation and usage of algorithms, chosen at run-time.

Quickly following learncpp.com for the c++ refresher.

IntArray created as first Data Structure.

Implemented the first Algorithm from CLRS: Insertion Sort.
*** Current CLRS page:
page 18
*** Current learncpp page:
https://www.learncpp.com/cpp-tutorial/timing-your-code/

*** Example Run:
#+begin_src elisp :exports both
  (shell-command-to-string projectile-project-run-cmd) 
#+end_src

#+RESULTS:
#+begin_example
Welcome to the DSA-runner
What Data Structure are we setting up?
Available Algorithms:
myAdd, myMult, 
full array: 
arr[0]:  4
arr[1]:  9
arr[2]:  2
arr[3]:  6

sorting the array...
sorted array..:
arr[0]:  0
arr[1]:  2
arr[2]:  4
arr[3]:  6

Time elapsed: 2.1942e-05 seconds
#+end_example

*** Click on Algorithms(.org||.pdf) to view the work there.

*** Data Structures
The same format will follow in the near future.

** Project - Specifics
*** tree

#+begin_src elisp :exports results
  ;; https://www.baeldung.com/linux/insert-line-specific-line-number
  ;; report of the directory structure, showing the build directory, but not it's contents
  (shell-command "tree -a -o tree.txt -I 'build|.cache|.git|tree.txt|ltximg'")
  (shell-command "sed -i '2 i ├── build' tree.txt")
  (shell-command "echo 'Plus the build/ directory' >> tree.txt")
  (shell-command-to-string "cat -b tree.txt") 
#+end_src

#+RESULTS:
#+begin_example
     1	.
     2	├── build
     3	├── Algorithms.org
     4	├── Algorithms.pdf
     5	├── Code_Notes.org
     6	├── .dir-locals.el
     7	├── doc
     8	│   └── code_scraps.org
     9	├── .gitignore
    10	├── lib
    11	│   ├── CMakeLists.txt
    12	│   ├── myTimer.cpp
    13	│   ├── readme.txt
    14	│   └── skipHeaders
    15	├── .projectile
    16	├── README.md
    17	├── README.org
    18	├── src
    19	│   ├── CMakeLists.txt
    20	│   ├── DSA_CLRS.cpp
    21	│   └── include
    22	│       ├── myAlgo
    23	│       │   ├── CMakeLists.txt
    24	│       │   ├── myAdd.cpp
    25	│       │   ├── myAlgorithms.cpp
    26	│       │   ├── myAlgorithms.hpp
    27	│       │   ├── myInsertionSort.cpp
    28	│       │   └── myMult.cpp
    29	│       └── myDS
    30	│           ├── CMakeLists.txt
    31	│           ├── IntArray.cpp
    32	│           ├── myDataStructures.cpp
    33	│           └── myDataStructures.hpp
    34	└── test
    35	    ├── commandsGDB
    36	    └── gdbInput1.txt

    37	7 directories, 27 files
    38	Plus the build/ directory
#+end_example




*** how to build, compile, and run
This build system is integrated with spacemacs.
**** build/compile:
run (cmake-ide-compile) while in DSA-CLRS.cpp
I have (cmake-ide-compile) bound to =,cc=
**** run:
run (omen-c/cpp-project-run-interactive-executable) while in DSA-CLRS.cpp
I have (omen-c/cpp-project-run-interactive-executable) bound to =<Spc> ocr=


* Git Repo: DSA-CLRS
https://github.com/kennethken73/DSA_CLRS
Remember to export to markdown from README.org
* C++ Project - Main Features
** Emacs Development Environment
*** Magit
*** lsp-mode
*** DAP-mode debugging
*** org-mode
**** literate programming
**** org-export with pandoc and markdown integration
*** dir-locals configuration
*** projectile configuration
*** non-conflicting with installed emacs packages
*** TODO
+ get Doxygen set up
+ get clang-format set up
** CMake Build Management
*** TODO
+ get clean-target working
+ set up running an input file into the main executable
  + this will be our testing method
  + so, we'll need a cmake target which reads from /test
    
    
